# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 115) do

  create_table "Copy_of_hejia_brand_product_news", :force => true do |t|
    t.column "product_id",      :integer
    t.column "type_id",         :integer
    t.column "title",           :string
    t.column "description",     :text
    t.column "author",          :string
    t.column "editor",          :string
    t.column "source",          :string
    t.column "news_source_url", :string
    t.column "news_created_at", :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "view_counter",    :integer,  :default => 1
  end

  create_table "activity_admins", :force => true do |t|
    t.column "admin_id",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "activity_vote_items", :force => true do |t|
    t.column "activity_id",  :integer
    t.column "vote_id",      :integer
    t.column "item_name",    :string
    t.column "vote_counter", :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "activity_votes", :force => true do |t|
    t.column "activity_id",      :integer
    t.column "subject",          :string
    t.column "description",      :string
    t.column "user_id",          :integer
    t.column "choice_num",       :integer
    t.column "allow_choice_num", :integer
    t.column "overdue_time",     :datetime
    t.column "allow_reply",      :integer
    t.column "reply_counter",    :integer
    t.column "vote_counter",     :integer
    t.column "view_counter",     :integer
    t.column "editor_id",        :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_authorized_users", :force => true do |t|
    t.column "user_id",           :integer
    t.column "authority_type_id", :integer
    t.column "is_valid",          :integer,  :default => 1, :null => false
    t.column "expired_at",        :datetime
    t.column "editor_id",         :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "ask_blocked_ips", :force => true do |t|
    t.column "ip",         :string,   :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_blocked_ips", ["id"], :name => "index_blocked_ip_id", :unique => true
  add_index "ask_blocked_ips", ["ip"], :name => "index_blocked_ip_ip"

  create_table "ask_blog_albums", :force => true do |t|
    t.column "user_id",           :integer
    t.column "album_name",        :string
    t.column "album_description", :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "ask_blog_categories", :force => true do |t|
    t.column "user_id",              :integer
    t.column "category_name",        :string
    t.column "category_description", :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  create_table "ask_blog_choices", :force => true do |t|
    t.column "sort_id",       :integer
    t.column "user_id",       :integer
    t.column "topic_type_id", :integer,  :default => 4
    t.column "topic_id",      :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "order_number",  :integer
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_blog_configs", :force => true do |t|
    t.column "user_id",          :integer
    t.column "blog_name",        :string
    t.column "blog_description", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_blog_sorts", :force => true do |t|
    t.column "sort_name",        :string
    t.column "sort_description", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_blog_states", :force => true do |t|
    t.column "user_id",    :integer
    t.column "is_active",  :integer,  :default => 1, :null => false
    t.column "is_edit",    :integer,  :default => 1, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_blog_statistics", :force => true do |t|
    t.column "user_id",    :integer
    t.column "source_url", :string
    t.column "visitor_id", :integer
    t.column "visitor_ip", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_blog_topic_posts", :force => true do |t|
    t.column "blog_topic_id", :integer
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "content",       :text
    t.column "is_delete",     :integer,  :default => 0, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_blog_topics", :force => true do |t|
    t.column "area_id",      :integer
    t.column "user_id",      :integer
    t.column "ip",           :string
    t.column "category_id",  :integer
    t.column "tag_id",       :integer
    t.column "subject",      :string
    t.column "description",  :text
    t.column "view_counter", :integer,  :default => 1, :null => false
    t.column "post_counter", :integer,  :default => 1, :null => false
    t.column "is_draft",     :integer,  :default => 0, :null => false
    t.column "is_top",       :integer,  :default => 0, :null => false
    t.column "is_use",       :integer,  :default => 0, :null => false
    t.column "is_delete",    :integer,  :default => 0, :null => false
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_company_comments", :force => true do |t|
    t.column "guest_name",         :string
    t.column "company_id",         :integer
    t.column "user_id",            :integer
    t.column "design_ability",     :integer
    t.column "buget_reasonality",  :integer
    t.column "construct_quality",  :integer
    t.column "after_source",       :integer
    t.column "recommend_designer", :string
    t.column "description",        :string
    t.column "ip",                 :string
    t.column "is_delete",          :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  create_table "ask_editor_choices", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "type_id",       :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "order_number",  :integer
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_editor_operations", :force => true do |t|
    t.column "editor_id",     :integer
    t.column "project_id",    :integer
    t.column "operation_id",  :integer
    t.column "operation_url", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_forum_admins", :force => true do |t|
    t.column "forum_tag_id", :integer
    t.column "admin_id",     :integer
    t.column "is_delete",    :integer,  :default => 0, :null => false
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_forum_choices", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "type_id",       :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "user_id",       :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "order_number",  :integer
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "description",   :string
  end

  create_table "ask_forum_tags", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_forum_tags", ["id"], :name => "index_forum_tag_id", :unique => true
  add_index "ask_forum_tags", ["name"], :name => "index_forum_tag_name"

  create_table "ask_forum_topic_posts", :force => true do |t|
    t.column "forum_topic_id", :integer,                 :null => false
    t.column "user_id",        :integer
    t.column "guest_email",    :string
    t.column "ip",             :string
    t.column "content",        :text
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "method",         :integer,                 :null => false
    t.column "editor_id",      :integer
    t.column "level_id",       :integer
  end

  add_index "ask_forum_topic_posts", ["id"], :name => "index_forum_topic_post_id", :unique => true
  add_index "ask_forum_topic_posts", ["created_at"], :name => "index_forum_topic_post_created_at"
  add_index "ask_forum_topic_posts", ["forum_topic_id"], :name => "index_forum_topic_post_topic_id"

  create_table "ask_forum_topics", :force => true do |t|
    t.column "area_id",         :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "tag_id",          :integer
    t.column "subject",         :string,                  :null => false
    t.column "method",          :integer,                 :null => false
    t.column "description",     :text
    t.column "reference",       :string
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "is_close",        :integer,  :default => 0, :null => false
    t.column "post_counter",    :integer,  :default => 1, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "editor_id",       :integer
    t.column "is_distribute",   :integer,  :default => 0
    t.column "source",          :string
    t.column "source_id",       :string
    t.column "reality_view",    :integer,                 :null => false
    t.column "view_counter",    :integer,  :default => 1, :null => false
    t.column "is_top",          :integer,  :default => 0, :null => false
    t.column "is_good",         :integer,  :default => 0, :null => false
    t.column "latest_reply_at", :datetime
    t.column "level_id",        :integer
  end

  add_index "ask_forum_topics", ["id"], :name => "index_forum_topic_id", :unique => true
  add_index "ask_forum_topics", ["subject"], :name => "index_forum_topic_subject"
  add_index "ask_forum_topics", ["tag_id"], :name => "index_forum_topic_tag_id"

  create_table "ask_hejia_companies", :force => true do |t|
    t.column "cn_name",                   :string
    t.column "address",                   :string
    t.column "tel",                       :string
    t.column "linkman",                   :string
    t.column "web_stage",                 :string
    t.column "country",                   :string
    t.column "area",                      :string
    t.column "type_id",                   :string
    t.column "guild_id",                  :string
    t.column "has_order_manager_feature", :integer,  :default => 0
    t.column "has_chat_manager_feature",  :integer,  :default => 0
    t.column "create_date",               :datetime
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "editor_id",                 :integer
    t.column "post_counter",              :integer,  :default => 1, :null => false
    t.column "view_counter",              :integer,  :default => 1, :null => false
    t.column "is_delete",                 :integer,  :default => 0, :null => false
    t.column "method",                    :integer,  :default => 1, :null => false
    t.column "area_id",                   :integer,  :default => 1
    t.column "user_id",                   :integer
    t.column "description",               :string
  end

  create_table "ask_hejia_company_posts", :force => true do |t|
    t.column "hejia_company_id", :integer,                 :null => false
    t.column "user_id",          :integer
    t.column "guest_email",      :string
    t.column "ip",               :string
    t.column "content",          :text
    t.column "is_delete",        :integer,  :default => 0, :null => false
    t.column "method",           :integer,                 :null => false
    t.column "editor_id",        :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_operations", :force => true do |t|
    t.column "name",        :string,   :null => false
    t.column "description", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_score_orders", :force => true do |t|
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_score", :integer,  :null => false
    t.column "version",         :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_search_keywords", :force => true do |t|
    t.column "area_id",    :integer,  :null => false
    t.column "type_id",    :integer,  :null => false
    t.column "keyword",    :string,   :null => false
    t.column "user_id",    :integer
    t.column "ip",         :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_statistics", :force => true do |t|
    t.column "app_controller", :string
    t.column "app_action",     :string
    t.column "visit_url",      :string
    t.column "visitor_id",     :integer
    t.column "visitor_ip",     :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_tag_links", :force => true do |t|
    t.column "start_id",    :integer,  :null => false
    t.column "end_id",      :integer,  :null => false
    t.column "link_weight", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_taolun_tags", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_taolun_topic_posts", :force => true do |t|
    t.column "taolun_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "content",         :text
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
  end

  create_table "ask_taolun_topics", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "tag_id",        :integer
    t.column "subject",       :string,                  :null => false
    t.column "method",        :integer,                 :null => false
    t.column "description",   :text
    t.column "reference",     :string
    t.column "is_delete",     :integer,  :default => 0, :null => false
    t.column "is_close",      :integer,  :default => 0, :null => false
    t.column "post_counter",  :integer,  :default => 1, :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1, :null => false
    t.column "is_top",        :integer,  :default => 0, :null => false
  end

  create_table "ask_tieba_topic_posts", :force => true do |t|
    t.column "tieba_topic_id", :integer,                 :null => false
    t.column "user_id",        :integer
    t.column "content",        :text
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_tieba_topics", :force => true do |t|
    t.column "area_id",      :integer,                 :null => false
    t.column "tieba_id",     :integer,                 :null => false
    t.column "user_id",      :integer,                 :null => false
    t.column "tag_id",       :integer,                 :null => false
    t.column "subject",      :string,                  :null => false
    t.column "method",       :integer,                 :null => false
    t.column "is_delete",    :integer,  :default => 0, :null => false
    t.column "post_counter", :integer,  :default => 1, :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_tiebas", :force => true do |t|
    t.column "area_id",      :integer,  :null => false
    t.column "user_id",      :integer,  :null => false
    t.column "name",         :string,   :null => false
    t.column "company_name", :string,   :null => false
    t.column "description",  :string
    t.column "sign",         :string
    t.column "icon_url",     :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_topic_reads", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_subscriptions", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "guest_email",   :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_tag_urls", :force => true do |t|
    t.column "tag_id",         :integer,  :null => false
    t.column "topic_url",      :string
    t.column "topic_url_type", :string
    t.column "topic_id",       :integer
    t.column "topic_type_id",  :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_topic_user_tags", :force => true do |t|
    t.column "user_tag_id",   :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
  end

  create_table "ask_user_infos", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "nickname",   :string
    t.column "sex",        :string
    t.column "sign",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_messages", :force => true do |t|
    t.column "send_user_id",    :integer
    t.column "receive_user_id", :integer
    t.column "content",         :string
    t.column "state",           :integer,  :default => 0, :null => false
    t.column "is_read",         :integer,  :default => 0, :null => false
    t.column "parent_id",       :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_user_operations", :force => true do |t|
    t.column "user_id",         :integer,  :null => false
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_count", :integer,  :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_user_scores", :force => true do |t|
    t.column "user_id",    :integer,                   :null => false
    t.column "score",      :integer,  :default => 100, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_tags", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_user_tags", ["id"], :name => "index_user_tag_id", :unique => true
  add_index "ask_user_tags", ["name"], :name => "index_user_tag_name"

  create_table "ask_user_uploads", :force => true do |t|
    t.column "type_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "user_id",      :integer
    t.column "ip",           :string
    t.column "path",         :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "album_id",     :integer
  end

  create_table "ask_wiki_catalogs", :force => true do |t|
    t.column "content_id",   :integer
    t.column "catalog_name", :string
    t.column "is_delete",    :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_wiki_contents", :force => true do |t|
    t.column "content_name", :string
    t.column "tag",          :string
    t.column "is_delete",    :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_wiki_items", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "content_id",  :integer
    t.column "catalog_id",  :integer
    t.column "is_delete",   :integer
    t.column "editor_id",   :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_zhidao_admins", :force => true do |t|
    t.column "admin_id",   :integer
    t.column "is_delete",  :integer,  :default => 0, :null => false
    t.column "editor_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_zhidao_editor_topics", :force => true do |t|
    t.column "editor_id",       :integer
    t.column "zhidao_topic_id", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_zhidao_editor_uploads", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_zhidao_topic_post_votes", :force => true do |t|
    t.column "zhidao_topic_post_id", :integer,  :null => false
    t.column "user_id",              :integer,  :null => false
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  create_table "ask_zhidao_topic_posts", :force => true do |t|
    t.column "zhidao_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "content",         :text
    t.column "vote_counter",    :integer,  :default => 1, :null => false
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "guest_name",      :string
  end

  add_index "ask_zhidao_topic_posts", ["id"], :name => "index_zhidao_topic_post_id", :unique => true
  add_index "ask_zhidao_topic_posts", ["zhidao_topic_id"], :name => "index_zhidao_topic_post_topic_id"

  create_table "ask_zhidao_topics", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "user_id",       :integer
    t.column "tag_id",        :integer
    t.column "subject",       :string,                  :null => false
    t.column "method",        :integer,                 :null => false
    t.column "description",   :text
    t.column "is_delete",     :integer,  :default => 0, :null => false
    t.column "is_close",      :integer,  :default => 0, :null => false
    t.column "best_post_id",  :integer
    t.column "post_counter",  :integer,  :default => 1, :null => false
    t.column "is_vote",       :integer,  :default => 0, :null => false
    t.column "vote_counter",  :integer,  :default => 1, :null => false
    t.column "score",         :integer,  :default => 0, :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1, :null => false
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "guest_name",    :string
    t.column "company_id",    :integer
  end

  add_index "ask_zhidao_topics", ["id"], :name => "index_zhidao_topic_id", :unique => true
  add_index "ask_zhidao_topics", ["subject"], :name => "index_zhidao_topic_subject"
  add_index "ask_zhidao_topics", ["tag_id"], :name => "index_zhidao_topic_tag_id"
  add_index "ask_zhidao_topics", ["created_at"], :name => "index_zhidao_topic_created_at"

  create_table "ask_zhishi_topic_posts", :force => true do |t|
    t.column "zhishi_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "content",         :text
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
  end

  add_index "ask_zhishi_topic_posts", ["id"], :name => "index_zhishi_topic_post_id", :unique => true

  create_table "ask_zhishi_topics", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "tag_id",        :integer
    t.column "subject",       :string,                  :null => false
    t.column "method",        :integer,                 :null => false
    t.column "description",   :text
    t.column "reference",     :string
    t.column "is_delete",     :integer,  :default => 0, :null => false
    t.column "is_close",      :integer,  :default => 0, :null => false
    t.column "post_counter",  :integer,  :default => 1, :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1, :null => false
  end

  add_index "ask_zhishi_topics", ["id"], :name => "index_zhishi_topic_id", :unique => true
  add_index "ask_zhishi_topics", ["subject"], :name => "index_zhishi_topic_subject"

  create_table "emails", :force => true do |t|
    t.column "from",              :string
    t.column "to",                :string
    t.column "last_send_attempt", :integer,  :default => 0
    t.column "mail",              :text
    t.column "created_on",        :datetime
  end

  create_table "estate_housing_designs", :force => true do |t|
    t.column "estate_id",           :integer
    t.column "housing_name",        :string
    t.column "housing_description", :string
    t.column "edito_id",            :integer
    t.column "is_del",              :integer,  :default => 0
    t.column "create_at",           :datetime
    t.column "updated_at",          :datetime
  end

  create_table "estate_housing_patterns", :force => true do |t|
    t.column "estate_id",      :integer
    t.column "hosuing_id",     :integer
    t.column "housing",        :string
    t.column "like_name",      :string
    t.column "design_idea1",   :string
    t.column "design_idea2",   :string
    t.column "design_idea3",   :string
    t.column "designer",       :string
    t.column "designer_blog",  :string
    t.column "view_counter",   :integer
    t.column "design_company", :string
    t.column "is_del",         :integer,  :default => 0
    t.column "editor_id",      :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "estate_housing_uploads", :force => true do |t|
    t.column "estate_id",      :integer
    t.column "hosuing_id",     :integer
    t.column "pattern_id",     :integer
    t.column "content_type",   :string
    t.column "filename",       :string
    t.column "thumbnail",      :string
    t.column "size",           :integer
    t.column "is_del",         :integer,  :default => 0
    t.column "is_method",      :integer
    t.column "editor_id",      :integer
    t.column "path",           :string
    t.column "description",    :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "designer",       :string
    t.column "designer_blog",  :string
    t.column "design_company", :string
    t.column "focus_id",       :integer
    t.column "store_id",       :integer
  end

  create_table "estate_infos", :force => true do |t|
    t.column "estate_name",        :string
    t.column "estate_description", :string
    t.column "editor_id",          :integer
    t.column "is_del",             :integer,  :default => 0
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  create_table "event_admins", :force => true do |t|
    t.column "admin_id",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "event_choice_styles", :force => true do |t|
    t.column "event_id",    :integer
    t.column "style_name",  :string
    t.column "editor_id",   :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "description", :string
  end

  create_table "event_choices", :force => true do |t|
    t.column "event_id",   :integer
    t.column "style_id",   :integer
    t.column "pic_name",   :string
    t.column "pic_url",    :string
    t.column "editor_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "event_user_uploads", :force => true do |t|
    t.column "event_id",     :integer
    t.column "style_id",     :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "user_id",      :integer
    t.column "ip",           :string
    t.column "path",         :string
    t.column "description",  :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "event_vote_items", :force => true do |t|
    t.column "event_id",     :integer
    t.column "vote_id",      :integer
    t.column "item_name",    :string
    t.column "vote_counter", :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "event_vote_replies", :force => true do |t|
    t.column "event_id",      :integer
    t.column "vote_id",       :integer
    t.column "description",   :string
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "user_id",       :integer
    t.column "reply_counter", :integer
    t.column "is_valid",      :integer,  :default => 0
  end

  create_table "event_votes", :force => true do |t|
    t.column "event_id",         :integer
    t.column "subject",          :string
    t.column "description",      :string
    t.column "user_id",          :integer
    t.column "choice_num",       :integer
    t.column "allow_choice_num", :integer
    t.column "overdue_time",     :datetime
    t.column "allow_reply",      :integer
    t.column "reply_counter",    :integer
    t.column "vote_counter",     :integer
    t.column "view_counter",     :integer
    t.column "editor_id",        :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "events", :force => true do |t|
    t.column "event_name",    :string
    t.column "event_company", :integer
    t.column "description",   :string
    t.column "start_time",    :datetime
    t.column "end_time",      :datetime
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "hejia_brand_categories", :force => true do |t|
    t.column "name",       :string
    t.column "en_name",    :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "hejia_brand_images", :force => true do |t|
    t.column "brand_id",     :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
  end

  create_table "hejia_brand_product_areas", :force => true do |t|
    t.column "name_zh",    :string
    t.column "name_en",    :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "hejia_brand_product_images", :force => true do |t|
    t.column "product_id", :integer
    t.column "image_path", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "hejia_brand_product_news", :force => true do |t|
    t.column "product_id",      :integer
    t.column "type_id",         :integer
    t.column "title",           :string
    t.column "description",     :text
    t.column "author",          :string
    t.column "editor",          :string
    t.column "source",          :string
    t.column "news_source_url", :string
    t.column "news_created_at", :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "view_count",      :integer,  :default => 1
  end

  create_table "hejia_brand_product_params", :force => true do |t|
    t.column "product_id",  :integer
    t.column "is_primary",  :integer,  :default => 0
    t.column "param_key",   :string
    t.column "param_value", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "hejia_brand_product_quotes", :force => true do |t|
    t.column "product_id",   :integer
    t.column "area_id",      :integer
    t.column "dealer",       :string
    t.column "quote",        :float
    t.column "phone_number", :string
    t.column "linkman",      :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "hejia_brand_product_reviews", :force => true do |t|
    t.column "product_id",        :integer
    t.column "title",             :string
    t.column "description",       :string
    t.column "user_id",           :integer
    t.column "review_created_at", :datetime
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "hejia_brand_products", :force => true do |t|
    t.column "brand_id",     :integer
    t.column "name",         :string
    t.column "quote_ref",    :float
    t.column "type",         :string
    t.column "image_count",  :integer
    t.column "review_count", :integer
    t.column "view_count",   :integer,  :default => 0
    t.column "source_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  add_index "hejia_brand_products", ["source_id"], :name => "source_id"

  create_table "hejia_brands", :force => true do |t|
    t.column "name",        :string
    t.column "cn_name",     :string,   :limit => 11
    t.column "category_id", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "hejia_index_columns", :force => true do |t|
    t.column "type_id",     :integer
    t.column "name",        :string
    t.column "description", :string
    t.column "is_valid",    :integer,  :default => 1, :null => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "hejia_index_columns_copy", :force => true do |t|
    t.column "type_id",     :integer
    t.column "name",        :string
    t.column "description", :string
    t.column "is_valid",    :integer,  :default => 1, :null => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "hejia_index_publish_ads", :force => true do |t|
    t.column "type_id",      :integer
    t.column "text",         :string
    t.column "replace_text", :string
    t.column "url",          :string
    t.column "image_url",    :string
    t.column "image_title",  :string
    t.column "image_desc",   :string
    t.column "is_valid",     :integer,  :default => 1, :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "hejia_index_publish_ads_copy", :force => true do |t|
    t.column "type_id",      :integer
    t.column "text",         :string
    t.column "replace_text", :string
    t.column "url",          :string
    t.column "image_url",    :string
    t.column "image_title",  :string
    t.column "image_desc",   :string
    t.column "is_valid",     :integer,  :default => 1, :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "hejia_index_publishes", :force => true do |t|
    t.column "publish_column_id", :integer
    t.column "index_id",          :integer
    t.column "entity_type_id",    :integer
    t.column "entity_id",         :integer
    t.column "title",             :string
    t.column "description",       :text
    t.column "resume",            :string
    t.column "url",               :string
    t.column "media_type_id",     :integer,  :default => 0, :null => false
    t.column "image_url",         :string
    t.column "entity_created_at", :datetime
    t.column "entity_updated_at", :datetime
    t.column "entity_expired_at", :datetime
    t.column "order_id",          :integer,  :default => 0, :null => false
    t.column "text_style_id",     :integer,  :default => 0, :null => false
    t.column "publish_time",      :datetime,                :null => false
    t.column "expire_time",       :datetime,                :null => false
    t.column "image_text_ad_id",  :integer
    t.column "text_ad_id",        :integer
    t.column "is_valid",          :integer,  :default => 0, :null => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "hejia_index_publishes_copy", :force => true do |t|
    t.column "publish_column_id", :integer
    t.column "index_id",          :integer
    t.column "entity_type_id",    :integer
    t.column "entity_id",         :integer
    t.column "title",             :string
    t.column "description",       :text
    t.column "resume",            :string
    t.column "url",               :string
    t.column "media_type_id",     :integer,  :default => 0, :null => false
    t.column "image_url",         :string
    t.column "entity_created_at", :datetime
    t.column "entity_updated_at", :datetime
    t.column "entity_expired_at", :datetime
    t.column "order_id",          :integer,  :default => 0, :null => false
    t.column "text_style_id",     :integer,  :default => 0, :null => false
    t.column "publish_time",      :datetime,                :null => false
    t.column "expire_time",       :datetime,                :null => false
    t.column "image_text_ad_id",  :integer
    t.column "text_ad_id",        :integer
    t.column "is_valid",          :integer,  :default => 0, :null => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "hejia_index_relations", :force => true do |t|
    t.column "left_index_id",   :integer
    t.column "right_index_id",  :integer
    t.column "relation_degree", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "hejia_index_tags", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "parent_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "hejia_sitemap_tag_relations", :force => true do |t|
    t.column "tagid1", :integer, :null => false
    t.column "tagid2", :integer, :null => false
  end

  add_index "hejia_sitemap_tag_relations", ["id"], :name => "index_hejia_sitemap_tag_relation_id", :unique => true

  create_table "hejia_sitemap_tags_copy", :force => true do |t|
    t.column "type_id",     :integer, :null => false
    t.column "name",        :string,  :null => false
    t.column "description", :string
    t.column "parent_id",   :integer
  end

  add_index "hejia_sitemap_tags_copy", ["id"], :name => "tags6_id", :unique => true
  add_index "hejia_sitemap_tags_copy", ["parent_id"], :name => "tags6_parent_id"

  create_table "hejia_tag_similarities", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "name",          :string,   :limit => 127
    t.column "other_tag_ids", :string
    t.column "similarity",    :integer,                 :default => 10
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

# Could not dump table "hejia_tags" because of following StandardError
#   Unknown type 'bit(1)' for column 'has_child'

# Could not dump table "hejia_tags_copy" because of following StandardError
#   Unknown type 'bit(1)' for column 'has_child'

  create_table "publish_columns", :force => true do |t|
    t.column "editor_id",   :integer
    t.column "name",        :string
    t.column "description", :string
    t.column "is_valid",    :integer,  :default => 1, :null => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "publish_contents", :force => true do |t|
    t.column "publish_column_id", :integer
    t.column "index_id",          :integer
    t.column "entity_type_id",    :integer
    t.column "entity_id",         :integer
    t.column "title",             :string
    t.column "description",       :text
    t.column "resume",            :string
    t.column "url",               :string
    t.column "image_url",         :string
    t.column "media_type_id",     :integer,  :default => 0,                           :null => false
    t.column "entity_created_at", :datetime
    t.column "entity_updated_at", :datetime
    t.column "entity_expired_at", :datetime
    t.column "order_id",          :integer,  :default => 0,                           :null => false
    t.column "text_style_id",     :integer,  :default => 0,                           :null => false
    t.column "publish_time",      :datetime
    t.column "expire_time",       :datetime, :default => '2050-01-01T00:00:00+00:00'
    t.column "is_valid",          :integer,  :default => 0,                           :null => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "publish_text_styles", :force => true do |t|
    t.column "style_key",   :integer
    t.column "style_value", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "publish_uploads", :force => true do |t|
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "created_at",   :datetime
    t.column "updated_ar",   :datetime
  end

  create_table "radmin_lsbfms", :force => true do |t|
    t.column "category", :string,   :limit => 127
    t.column "lsbfmc1",  :string
    t.column "lsbfmc2",  :text
    t.column "lsbfmc3",  :string,   :limit => 127
    t.column "lsbfmc4",  :string,   :limit => 127
    t.column "lsbfmc5",  :string,   :limit => 127
    t.column "cdate",    :datetime
    t.column "udate",    :datetime
  end

  create_table "radmin_users", :force => true do |t|
    t.column "name",        :string,   :limit => 127, :default => "",                    :null => false
    t.column "password",    :string,   :limit => 127, :default => "",                    :null => false
    t.column "rname",       :string,   :limit => 127
    t.column "cdate",       :datetime,                :default => '1999-12-31 00:00:00', :null => false
    t.column "udate",       :datetime,                :default => '1999-12-31 00:00:00', :null => false
    t.column "idate",       :datetime,                :default => '1999-12-31 00:00:00', :null => false
    t.column "role",        :integer,  :limit => 127, :default => 0,                     :null => false
    t.column "description", :string
  end

  add_index "radmin_users", ["name"], :name => "name", :unique => true

  create_table "radmin_webpms", :force => true do |t|
    t.column "keyword",     :string,   :limit => 127
    t.column "value",       :string,   :limit => 127
    t.column "sort",        :integer,  :limit => 127
    t.column "description", :string,   :limit => 127
    t.column "cdate",       :datetime
    t.column "udate",       :datetime
  end

  add_index "radmin_webpms", ["keyword", "value"], :name => "index1", :unique => true

  create_table "replies", :force => true do |t|
    t.column "area_id",        :integer
    t.column "type_id",        :integer
    t.column "entity_id",      :integer
    t.column "entity_summary", :text
    t.column "user_id",        :integer
    t.column "guest_email",    :string
    t.column "ip",             :string
    t.column "content",        :string
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "editor_id",      :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  add_index "replies", ["entity_id"], :name => "index_reply_entity_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "siteindex_channel_zone_infos", :force => true do |t|
    t.column "channel_id",     :integer,                 :null => false
    t.column "type_id",        :integer,                 :null => false
    t.column "title",          :string
    t.column "description",    :text
    t.column "url",            :string
    t.column "sort_num",       :integer
    t.column "image_url",      :string
    t.column "comments_main",  :text
    t.column "comments_other", :text
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "is_del",         :integer,  :default => 0
    t.column "a_id",           :integer
  end

  create_table "siteindex_channel_zone_others", :force => true do |t|
    t.column "is_del",     :integer,  :default => 0
    t.column "title",      :string
    t.column "url",        :string
    t.column "image_url",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "type_name",  :string
    t.column "type_id",    :integer
  end

  create_table "siteindex_channel_zones", :force => true do |t|
    t.column "channel_name", :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "redian_id",    :integer
    t.column "jiaodian_id",  :integer
    t.column "is_del",       :integer,  :default => 0
  end

  create_table "siteindex_editor_uploads", :force => true do |t|
    t.column "channel_info_id", :integer
    t.column "path",            :string
    t.column "parent_id",       :integer
    t.column "content_type",    :string
    t.column "filename",        :string
    t.column "thumbnail",       :string
    t.column "size",            :integer
    t.column "width",           :integer
    t.column "height",          :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "link",            :string
  end

  create_table "soufun_house_info_around", :force => true do |t|
    t.column "source_id",       :integer
    t.column "house",           :string
    t.column "price",           :string
    t.column "around_config",   :string
    t.column "store",           :string
    t.column "estate_infos_id", :integer
  end

  create_table "soufun_house_infos", :id => false, :force => true do |t|
    t.column "source_id",             :integer, :default => 0, :null => false
    t.column "name",                  :string
    t.column "wuye_leibie",           :string
    t.column "jianzhu_leibie",        :string
    t.column "zhuangxiu_zhuangkuang", :string
    t.column "wuye_dizhi",            :string
    t.column "huanxian_dizhi",        :string
    t.column "suoshu_sq",             :string
    t.column "kaipan_time",           :string
    t.column "ruzhu_time",            :string
    t.column "rongjilv",              :string
    t.column "lvhualv",               :string
    t.column "wuye_fei",              :string
    t.column "wuye_gs",               :string
    t.column "kaifashang",            :string
    t.column "soulou_dizhi",          :string
    t.column "dangqian_junjia",       :string
    t.column "project_desc",          :text
    t.column "jiaotong_zhuangkang",   :text
  end

  create_table "tags", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "tags", ["id"], :name => "index_tag_id", :unique => true
  add_index "tags", ["name"], :name => "index_tag_name"
  add_index "tags", ["parent_id"], :name => "index_tag_parent_id"

  create_table "user_events", :force => true do |t|
    t.column "user_id",      :integer
    t.column "event_id",     :integer
    t.column "event_status", :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "user_infos", :force => true do |t|
    t.column "real_name",  :string
    t.column "tel",        :string
    t.column "address",    :string
    t.column "email",      :string
    t.column "mobile",     :string
    t.column "created_at", :datetime
    t.column "postcode",   :string
    t.column "updated_at", :datetime
    t.column "area",       :string
    t.column "status",     :integer
    t.column "event_id",   :integer
  end

  create_table "vote_details", :force => true do |t|
    t.column "event_id",    :integer
    t.column "vote_id",     :integer
    t.column "vote_detail", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "wiki_contents", :force => true do |t|
    t.column "name",         :string
    t.column "wiki_content", :text
    t.column "tag",          :string
    t.column "is_del",       :integer
    t.column "wiki_del",     :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "wiki_descripts", :force => true do |t|
    t.column "content_id",  :integer
    t.column "title",       :string
    t.column "description", :text
    t.column "is_del",      :integer
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
  end

end
